-- Plugin sources managed by Neovim's built-in package manager.
-- vim.pack was added in Neovim 0.12. Plugins are installed/updated here;
-- requiring their Lua modules is still done by your config as needed.
vim.pack.add({
	"https://github.com/ollykel/v-vim",
	"https://github.com/saghen/blink.cmp",
	"https://github.com/alaviss/nim.nvim",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/folke/trouble.nvim",
	"https://github.com/nvim-mini/mini.nvim",
	"https://github.com/jiaoshijie/undotree",
	"https://github.com/thePrimeagen/harpoon",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/nvim-orgmode/orgmode",
	"https://github.com/windwp/nvim-autopairs",
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/mfussenegger/nvim-lint",
	"https://github.com/akinsho/org-bullets.nvim",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/norcalli/nvim-colorizer.lua",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/rafamadriz/friendly-snippets",
	"https://github.com/nvim-telescope/telescope.nvim",
	"https://github.com/mason-org/mason-lspconfig.nvim",
	"https://github.com/nvim-treesitter/nvim-treesitter",
	"https://github.com/brenoprata10/nvim-highlight-colors",
	"https://github.com/antosha417/nvim-lsp-file-operations",
	"https://github.com/nvim-telescope/telescope-ui-select.nvim",
	"https://github.com/MeanderingProgrammer/render-markdown.nvim",
})
